### ISSUE TITLE
What if I aim on depositing my data for example in ENA?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#120]
Imagine that I know that at the end, I want to deposit the data for example in ENA but I have no idea, whether and which of the metadata format are they using/enforcing the submitters to use. Maybe the introductory part of this question could contain links for the most relevant data archives so that one can track it down - or at least know where to start digging,...

**Comment by tinavisnovska** [comment]
This is related to III. Creating and collecting data, 4. How will you be collecting and keeping your metadata?

**Comment by korbinib** [comment]
solved upstream
