### ISSUE TITLE
Tagging in data sensitivity chapter

### ISSUE THREAD

**Issue by bianchini88** [elixir-no-nels/DSW-ELIXIR-NO-feedback#124]
Many of the questions here are tagged with "NeLS storage request". Since these tags are well visible and appear all over the page, this might give the user the impression that NeLS would be the proper solution when dealing with sensitive data, which is obviously not the case. Can this feature be changed in a meaningful way? Would it be a good idea to introduce e.g. a sensible data tag or even make it something more tailored towards TSD?

**Comment by korbinib** [comment]
We want the question to be answered for NeLS storage request to exclude that NeLS will host sensitive data.

**Comment by bianchini88** [comment]
Right, but follow-up questions are not forced to have the same tag as the parent and removing this recurring tag might help contain the confusion. A warning about NeLS not being suitable for human data might also help and would probably clarify the reasoning behind the tag. 

Another tricky case would be a user that knows that sensitive data is not for NeLS and would exclude the "NeLS storage request" and "Sigma2" already at the beginning (because he/she knows already TSD will be the way to go). In this case, the chapter would be empty, which is not desirable considering the user did not do anything wrong.
