### ISSUE TITLE
1.a.1.a.1.a.11.c.2 In what form will the data sets be stored?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#125]
It would be useful to have explained the used terms "irevocably anonymised" and "pseudonymised" and maybe what it means in the context of genomics data - if this makes sense.

**Comment by korbinib** [comment]
This is maybe something more for a comment in a template than the guidance text?
