### ISSUE TITLE
include sample collection into III. Creating and collecting data 

### ISSUE THREAD

**Issue by tinavisnovska** [elixir-no-nels/DSW-ELIXIR-NO-feedback#126]
maybe include info about sample collection - this makes sense to me in the hospital setting - keeping records about how, when and where the sample collection is/will be done - not sure how much sense this makes in other settings.

**Comment by korbinib** [comment]
would also make sense for e.g. GGBN- partially covered by the biobank section I guess?

**Comment by tinavisnovska** [comment]
yes, partially covered by "8 Will you be storing physical samples?" but if I do not plan to store the samples (because they are stored somewhere else already), then I won't even get to that set of questions in the form. In such a situation it makes more sense to me to have a possibility to record where and by whom the samples are stored instead of filling in details about how exactly they are stored..

**Comment by korbinib** [comment]
Yes, but there is also the 00db6502-2f1f-4c39-beeb-dead2e7076ed "Will you couple existing (biobank) data sets?" tree

**Comment by tinavisnovska** [comment]
Yes, but this "Will you couple existing (biobank) data sets?"  tree does not fit my case. ;)

The "1.b.1 Will you be using any pre-existing data (including other people's data)?" is a follow up question after questions "1 Is there any pre-existing data?" and "1.b.1 Will you be using any pre-existing data (including other people's data)?" are both answered "yes".

Now imagine that I am getting patient samples directly from a clinic at a hospital to further work with them and to generate data. The samples are most likely stored somewhere at the hospital (I still need to figure the details out), but my answer to both questions "1." and "1.b.1" would be "no" and I'd never get to answer the "1.b.1.b.3" question.

**Comment by korbinib** [comment]
I understand the example. I would think 'pre-exisiting' data include patient records (phenotypic data). In any case I would expect this is considered as biobank as by the [health research act](https://lovdata.no/lov/2008-06-20-44/§25).
Taking your comments into account we should think about how to change the trees for the next release.

**Comment by korbinib** [comment]
fixed by upstream changes
