### ISSUE TITLE
3.a.1.b.3.b.2 Who will take care of authentication of potential users?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#130]
Consider that I select the answer "a. In a domain repository (like EBI's EGA) that arranges restricted access" in the previous question (3.a.1.b.3.b.1) am I expected to know how they do authentication for that particular repository or could you add some text on how can I decide which option to choose?

**Comment by korbinib** [comment]
we should maybe narrow this, indeed. Authorization is the 2nd question.
