### ISSUE TITLE
3.a.1.b.3.b.3 Who will take care of authorization of potential users?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#131]
Does "project member" denote the same entity as "contributor" in I. Administrative information or is it more of an entity on the level of institutions? The term is not defined anywhere in the form as far as I remember..

If "project member" is an institution, imagine that a data protection officer of the institution authorises potential users. In such a case answers "a. One of the project members will authorize" and "c. We will make use of an existing data access committee" both seem to me to describe the situation equally well, however the first of them is considered bad from the accessibility point of view and the other is considered good.

**Comment by korbinib** [comment]
No the DAA should be a separate committee ideally. But often a) is easier to implement. But we should refine the description I guess then.
