### ISSUE TITLE
Section V 3.b.6

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#137]
Guarantee instead of guaranty. The latter form is specific to a legal agreement.

**Comment by bianchini88** [comment]
For reference, this is the question "Do you plan taking special measures to guaranty the integrity of tools in the workflow?".
As far as I understand it, "guaranty" can be used only as a noun, so this indeed needs to be fixed.

**Comment by bianchini88** [comment]
I also changed "taking" with "to take"
