### ISSUE TITLE
5.b.1.a.5 Is special care needed to get the raw data ready for processing?

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-no-nels/DSW-ELIXIR-NO-feedback#146]
We can improve it by rephrasing following options:

a. No, this is all fine
b. Yes, lets explore this

Suggestion:

a. No further processing is required to obtain raw data
b. Further steps are required for preparation of raw data

I think it may also be helpful if description includes an example.

**Comment by bianchini88** [comment]
>a. No further processing is required to obtain raw data
Probably "obtain" is not the right word here. 

Personally, I think this actually works as a yes/no question. 
If we keep it as it is, we need to at least change "lets" with "let us".

I agree it might be useful to have an example. However, examples tend 
to be very much domain-specific and I am not entirely sure we want this 
in the KM directly. We could consider adding examples of this kind through 
comments in the domain templates.
