### ISSUE TITLE
1.b.1.b.2.a.1.a.6 Is extension of any consent for privacy sensitive data needed?

### ISSUE THREAD

**Issue by Nazeeefa** [elixir-no-nels/DSW-ELIXIR-NO-feedback#153]
The description for this question in exemplary DMP "non-quantitative NGS of non-human sample" (tag: Template) says:

"If the data that you will re-use is **coupled to people**, the informed consent that was originally obtained from **those people** may not be covering your current research. In that case re-consent may be necessary."

It needs to be rephrased as the DMP is for non-human data only.

Same changes need to be applied to 1.b.1.b.2.a.1.b.6

**Comment by korbinib** [comment]
![image](https://user-images.githubusercontent.com/58505673/149895957-e8b83175-b1e0-4871-914f-f9ab42923caa.png)

This is a general remark in the KM, I don't see why we should change it for one application (creating a fork). I think this is un-ambigous with the recommendation by the template?

**Comment by bianchini88** [comment]
@korbinib @Nazeeefa This is a "wontfix", right? Shall we just be closing it?
