### ISSUE TITLE
Only 1 role allowed by design

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#17]
Is only 1 role allowed by design? Often same user will have many roles, and which to prioritize to list here is far from evident.

**Comment by korbinib** [comment]
Yes this is a flaw of the underling form design and cannot be fixed on a knowledge model level

**Comment by korbinib** [comment]
related Jira issue [DSW-397](https://ds-wizard.atlassian.net/projects/DSW/issues/DSW-397)
