### ISSUE TITLE
Multiple choices for roles?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#50]
Is it possible that a member of a project has multiple-roles, for example both data collector & data manager? Could we enable multiple choices for this question?

**Comment by korbinib** [comment]
Not implemented in DSW yet

**Comment by korbinib** [comment]
Duplicate of #17
related Jira issue [DSW-397](https://ds-wizard.atlassian.net/projects/DSW/issues/DSW-397)
