### ISSUE TITLE
Examples of data size

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#66]
Would anyone know how large an average mass-spec file is? Maybe add some general info for an example 1 raw mass spec file is estimated 1 gb and so on, are you planning to use faims? etc. If you plan to use PD files, the size will increase with (...) depending on how many files you have.

**Comment by korbinib** [comment]
Good idea. But we also should offer similar guidance for other technologies (NGS, imaging, ...)
