### ISSUE TITLE
4.b.1List the ontologies you will be using

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#83]
I feel this part is redundant, as we have "2What existing encodings/terminologies/vocabularies/ontologies will you be using?". Also, the latter is more advanced, as it contains the integration which is not available here (user have to provide the link)

**Comment by alexgade** [comment]
Can we link the responses here to the ontologies listed in part III. creating and collecting data? I remember there was another section where a link was requested for similar questions regarding data intellectual property.
