### ISSUE TITLE
1.b.1.b.1What reference data will you use?

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#86]
Question for data reuse (1.b.1.b.1 and 1.b.1.b.1.b.1 and 1.b.1.b.1.b.2) would it be better just to ask for the URL/PID/DOI of the dataset and that’s it?

**Comment by korbinib** [comment]
external comment: Where the data is available may change with time and the user may not know it.
Is it worth changing the question ‘What are the conditions of use for this database or dataset’ to ‘do you have permission to use the database or dataset?’
